@jwt = 

### actors-index
GET http://localhost:3000/actors.json 

### create-actors
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "S", 
  "last_name": "B",
  "known_for": "good stuff",
  "age": "8"
}

### update-actors

PATCH http://localhost:3000/actors/10
Content-Type: application/json

{
  "known_for": "Miss Congeniality"
}

### delete-actors

DELETE http://localhost:3000/actors/11
Content-Type: application/json

### movies index
GET http://localhost:3000/movies.json


### create-movies

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Twilight",
  "year": 2008,
  "plot": "vampires and werewolves are yummy",
  "director": "David Slade",
  "english": "true"
}

### update-movies

PATCH http://localhost:3000/movies/9
Content-Type: application/json

{
  "plot": "everyone seeks magic lands magic"
}

### delete-movies

DELETE http://localhost:3000/movies/8
Content-Type: application/json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Natasha Romanoff",
  "email": "blackwidow@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Movies create with auth
POST http://localhost:3000/movies.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title":
  "year": 
  "plot": 
}
### MovieGenre create
POST http://localhost:3000/movie_genres.json
Content-Type: application/json

{
  "genre_id": 4,
  "movie_id": 7
}