
### create-actors
POST http://localhost:3000/actors/
Content-Type: application/json

{
  "first_name": "Sandra", 
  "last_name": "Bullock",
  "known_for": "Speed"
}

### update-actors

PATCH http://localhost:3000/actors/10
Content-Type: application/json

{
  "known_for": "Miss Congeniality"
}

### delete-actors

DELETE http://localhost:3000/actors/11
Content-Type: application/json

### create-movies

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Twilight",
  "year": 2008,
  "plot": "vampires and werewolves are yummy",
  "director": "David Slade",
  "english": "true"
}

### update-movies

PATCH http://localhost:3000/movies/5
Content-Type: application/json

{
  "english": "true"
}

### delete-movies

DELETE http://localhost:3000/movies/6
Content-Type: application/json
